name: Build (Fabric 1.20.4)

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Gradle 8.7 (no wrapper needed)
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.7'
          cache-read-only: false

      - name: Show Gradle version
        run: gradle --version

      - name: Build
        run: gradle --stacktrace --no-daemon --warning-mode=all --refresh-dependencies clean build remapJar

      - name: Upload all jars
        uses: actions/upload-artifact@v4
        with:
          name: buildcraft-fabric-jars
          path: |
            build/libs/*.jar
