      - name: Build (clean + remap)
        env:
          JAVA_TOOL_OPTIONS: ""
          JAVA_OPTS: ""
          GRADLE_OPTS: "-Djava.net.preferIPv4Stack=true -Dhttps.protocols=TLSv1.2,TLSv1.3"
        run: |
          ./gradlew clean remapJar -S --stacktrace --no-daemon

      - name: Show built jars
        run: |
          echo "Jars under build/libs:"
          find . -type f -path "*/build/libs/*.jar" -print -exec ls -lh {} \;

      - name: Resolve release jar
        id: jar
        shell: bash
        run: |
          set -euo pipefail
          # pick a non-dev, non-sources jar (Fabric Loom’s remapped output)
          mapfile -t C < <(find . -type f -path "*/build/libs/*.jar" \
            | grep -v -- '-sources\.jar$' \
            | grep -v -- '-dev\.jar$' \
            | sort)
          if [ ${#C[@]} -eq 0 ]; then
            echo "No release jar found in */build/libs/*.jar"; exit 1
          fi
          echo "Found release jar: ${C[0]}"
          echo "jar=${C[0]}" >> "$GITHUB_OUTPUT"

      - name: Upload release jar
        uses: actions/upload-artifact@v4
        with:
          name: mod-build
          path: ${{ steps.jar.outputs.jar }}
          if-no-files-found: error
