name: BuildCraft Fabric CI

on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Set up JDK 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', 'settings.gradle', 'gradle.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Prepare gradlew
        shell: bash
        run: |
          if [ -f gradlew ]; then
            sed -i 's/\r$//' gradlew
            chmod +x gradlew
            # Clear wrapper JVM opts if your wrapper had bad "-Xmx" defaults
            if grep -q '^DEFAULT_JVM_OPTS=' gradlew; then
              sed -i 's/^DEFAULT_JVM_OPTS=.*/DEFAULT_JVM_OPTS=""/' gradlew
            fi
          fi

      - name: Build (clean -> build -> remapJar)
        shell: bash
        env:
          JAVA_TOOL_OPTIONS: ""
          GRADLE_OPTS: "-Djava.net.preferIPv4Stack=true -Dhttps.protocols=TLSv1.2,TLSv1.3"
        run: |
          ./gradlew --refresh-dependencies clean build remapJar -S --no-daemon

      - name: List jars
        shell: bash
        run: |
          echo "Built jars:"
          find . -type f -path "*/build/libs/*.jar" -print | sort

      - name: Upload jars
        uses: actions/upload-artifact@v4
        with:
          name: buildcraft-fabric-jars
          path: "**/build/libs/*.jar"
          if-no-files-found: error
