name: Build (Fabric 1.20.4)

on:
  push:
    branches: [ main, master ]
    paths-ignore:
      - '**/*.md'
      - '**/*.png'
      - '**/*.jpg'
      - '**/*.gif'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
      - uses: actions/checkout@v4

      # Wrapper validation often trips repos that re-bootstrap the wrapper;
      # keep it but don't fail the whole build if it complains.
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2
        continue-on-error: true

      - name: Set up Temurin JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable (just in case)
        run: chmod +x gradlew

      - name: Build (assemble + remap)
        run: ./gradlew clean build remapJar --stacktrace --no-daemon

      - name: Upload mod JARs
        uses: actions/upload-artifact@v4
        with:
          name: buildcraft-fabric-jars
          path: |
            build/libs/*.jar
            !build/libs/*-sources.jar
            !build/libs/*-dev.jar
            !build/libs/*-javadoc.jar
          if-no-files-found: error
