name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Normalize gradlew line endings
        shell: bash
        run: |
          awk 'sub("\r$","")' gradlew > gradlew.nix && mv gradlew.nix gradlew
          chmod +x gradlew

      - name: Clear wrapper DEFAULT_JVM_OPTS safely
        shell: bash
        run: |
          python3 -c "import re, pathlib; p=pathlib.Path('gradlew'); s=p.read_text(encoding='utf-8'); s=re.sub(r'^DEFAULT_JVM_OPTS=.*$', 'DEFAULT_JVM_OPTS=\"\"', s, flags=re.M); p.write_text(s, encoding='utf-8')"
          chmod +x gradlew

      - name: Build (refresh deps)
        env:
          JAVA_TOOL_OPTIONS: ""
          JAVA_OPTS: ""
          GRADLE_OPTS: "-Djava.net.preferIPv4Stack=true -Dhttps.protocols=TLSv1.2,TLSv1.3"
        run: ./gradlew --refresh-dependencies build -S --stacktrace --no-daemon

      - name: Publish build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mod-build
          path: |
            build/libs/*.jar
            **/build/libs/*.jar
