name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # 👇 Fix: make wrapper executable on the runner
      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build --stacktrace --no-daemon

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: buildcraft-fabric-1.20.4-jar
          path: build/libs/*.jar
