name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # Normalize CRLF to LF to avoid "-Xmx64m" class errors
      - name: Normalize Gradle wrapper line endings
        run: |
          sudo apt-get update
          sudo apt-get install -y dos2unix
          if [ -f gradlew ]; then dos2unix gradlew; fi
          if [ -f gradle/wrapper/gradle-wrapper.properties ]; then dos2unix gradle/wrapper/gradle-wrapper.properties; fi

      # Ensure gradlew is executable (no-op if it already is)
      - name: Make Gradle wrapper executable
        run: |
          if [ -f gradlew ]; then chmod +x gradlew; fi

      # Try the wrapper; if it fails, install Gradle and generate a new wrapper (fallback)
      - name: Gradle version (with fallback)
        shell: bash
        run: |
          set -e
          if [ -f gradlew ]; then
            if ./gradlew --version; then
              echo "Gradle wrapper OK"
            else
              echo "Wrapper failed; installing Gradle via SDKMAN and generating wrapper..."
              curl -s "https://get.sdkman.io" | bash
              source "$HOME/.sdkman/bin/sdkman-init.sh"
              sdk install gradle 8.7
              gradle --version
              gradle wrapper --gradle-version 8.7
              chmod +x gradlew
              ./gradlew --version
            fi
          else
            echo "No gradlew found; installing Gradle via SDKMAN and generating wrapper..."
            curl -s "https://get.sdkman.io" | bash
            source "$HOME/.sdkman/bin/sdkman-init.sh"
            sdk install gradle 8.7
            gradle wrapper --gradle-version 8.7
            chmod +x gradlew
            ./gradlew --version
          fi

      # Optional: generate placeholder audio (safe to skip if ffmpeg missing)
      - name: Generate placeholder audio
        run: |
          python3 tools/generate_placeholder_sounds.py --ogg || true

      # Gradle cache (speeds up builds)
      - name: Setup Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew build --stacktrace --no-daemon

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: buildcraft-fabric-1.20.4-jar
          path: build/libs/*.jar
