name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build (refresh deps)
        run: ./gradlew --refresh-dependencies build -S --stacktrace --no-daemon
        env:
          GRADLE_OPTS: "-Djava.net.preferIPv4Stack=true -Dhttps.protocols=TLSv1.2,TLSv1.3"

      - name: Publish build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mod-build
          path: |
            build/libs/*.jar
            **/build/libs/*.jar
