name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # Fix Windows line endings breaking the Gradle wrapper on Linux
      - name: Normalize line endings for Gradle wrapper
        run: |
          sed -i 's/\r$//' gradlew
          sed -i 's/\r$//' gradle/wrapper/gradle-wrapper.properties

      # Ensure the wrapper is executable
      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      # (Optional) Generate placeholder audio (safe to skip if ffmpeg missing)
      - name: Generate placeholder audio
        run: |
          python3 tools/generate_placeholder_sounds.py --ogg || true

      # Gradle cache (speeds up builds)
      - name: Setup Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Gradle version
        run: ./gradlew --version

      - name: Build with Gradle
        run: ./gradlew build --stacktrace --no-daemon

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: buildcraft-fabric-1.20.4-jar
          path: build/libs/*.jar
