name: CI

on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'gradle'

      - name: Install Gradle 8.7 (no wrapper)
        shell: bash
        run: |
          set -euo pipefail
          curl -L -o gradle.zip https://services.gradle.org/distributions/gradle-8.7-bin.zip
          unzip -q gradle.zip
          echo "$PWD/gradle-8.7/bin" >> "$GITHUB_PATH"
          gradle --version

      - name: Build (clean + remap)
        env:
          GRADLE_OPTS: -Dhttps.protocols=TLSv1.2,TLSv1.3
        run: |
          set -euo pipefail
          gradle --stacktrace --no-daemon --refresh-dependencies clean build remapJar
          echo "Artifacts in build/libs:"
          ls -alh build/libs || true

      - name: Upload jars
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mod-jars
          path: |
            build/libs/*.jar
