name: Fix Gradle Wrapper

on:
  workflow_dispatch:

jobs:
  fix:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up JDK 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Detect broken or missing wrapper
        id: check
        shell: bash
        run: |
          set -euo pipefail
          NEED_FIX=false
          if [[ ! -f gradlew ]]; then NEED_FIX=true; fi
          if [[ ! -s gradle/wrapper/gradle-wrapper.jar ]]; then NEED_FIX=true; fi
          echo "need_fix=$NEED_FIX" >> "$GITHUB_OUTPUT"

      - name: Bootstrap Gradle and regenerate wrapper
        if: steps.check.outputs.need_fix == 'true'
        shell: bash
        run: |
          set -euo pipefail
          GRADLE_VER=8.7
          curl -sL "https://services.gradle.org/distributions/gradle-${GRADLE_VER}-bin.zip" -o gradle.zip
          unzip -q gradle.zip -d "$RUNNER_TEMP/gradle"
          export GRADLE_HOME="$RUNNER_TEMP/gradle/gradle-${GRADLE_VER}"
          export PATH="$GRADLE_HOME/bin:$PATH"
          gradle --version
          gradle wrapper --gradle-version "${GRADLE_VER}"
          chmod +x gradlew

      - name: Commit wrapper files
        if: steps.check.outputs.need_fix == 'true'
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add gradlew gradlew.bat gradle/wrapper/gradle-wrapper.properties gradle/wrapper/gradle-wrapper.jar
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "CI: regenerate Gradle wrapper"
          git push

      - name: Verify wrapper
        shell: bash
        run: |
          set -euo pipefail
          ./gradlew --version
