name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Gradle 8.7 (no wrapper needed)
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.7'
          cache-read-only: false

      - name: Build
        run: gradle --stacktrace --no-daemon --warning-mode=all clean build remapJar

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/*.jar
          generate_release_notes: true
